---
title: "ANLY 530 Group Assignment (Laboratory 3: Mixed Methods or Semi-Supervised Learning)"
author:
- "Josseline Betio"
- "Akpany Benjamin Ebby"
- "Yajun Wang"
- "Salah Eddine MIFDAL"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    highlight: zenburn
comment: Rmd Document with Markdown + Embedded R Code
---

---

#### Document as of `r Sys.Date()`

```{r setup, include=FALSE, purl=FALSE, eval=TRUE}

source('R/ANLY530_Laboratory3_Helper.R')

```

```{r echo=FALSE}

library(knitr)
library(kableExtra)
read_chunk('R/ANLY530_Laboratory3_Chunks.R')

```

Some helper functions do exists to support the code snippets below such as: ```fullFilePath```

---

```{r loadLibraries, message=FALSE, warning=FALSE}
```

## Collecting the data

Let us start by [Loading the Data Sheets]

```{r loadSheets, message=FALSE, warning=FALSE}
```

# Part 3:
-------------

## Wine Data:

```{r partWineDataPrep, message=FALSE, warning=FALSE}
```

```{r part3Wine, message=FALSE, warning=FALSE}
```

## Analysis

TODO

---

# Appendix:

### Required Libraries

```{r installLibraries, eval=FALSE}
```

```{r loadLibraries, eval=FALSE}
```

### Helper Functions

```{r helperFunctions, eval=FALSE}
```

### Loading the Data Sheets

```{r loadSheets, eval=FALSE}
```

